[package]
name = "cryptopals"
version = "0.1.0"
authors = ["Jordan Stephens <jordan@stephens.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ordered-float = "1.0.2"
rayon = "1.3.0"
